pub use makepad_icon;
pub use makepad_widgets;

use makepad_widgets::*;

pub mod accordion;
pub mod alert;
pub mod dialog;
pub use dialog::ShadDialog;
pub use sonner::ShadSonner;
pub mod aspect_ratio;
pub mod avatar;
pub mod badge;
pub mod breadcrumb;
pub mod button;
pub mod button_group;
pub mod card;
pub mod carousel;
pub use carousel::ShadCarousel;
pub mod checkbox;
pub mod collapsible;
pub mod drawer;
pub mod dropdown_menu;
pub mod hover_card;
pub mod hr;
pub mod input;
pub mod kbd;
pub mod label;
pub mod panel;
pub mod progress;
pub mod radio_group;
pub mod resizable;
pub mod scroll;
pub mod select;
pub mod sheet;
pub mod sidebar;
pub mod skeleton;
pub mod slider;
pub mod sonner;
pub mod spinner;
pub mod switch;
pub mod tabs;
pub mod theme;
pub mod tooltip;

pub fn script_mod(vm: &mut ScriptVm) {
    makepad_icon::script_mod(vm);
    crate::theme::script_mod(vm);
    crate::accordion::script_mod(vm);
    crate::alert::script_mod(vm);
    crate::aspect_ratio::script_mod(vm);
    crate::avatar::script_mod(vm);
    crate::badge::script_mod(vm);
    crate::breadcrumb::script_mod(vm);
    crate::button::script_mod(vm);
    crate::button_group::script_mod(vm);
    crate::card::script_mod(vm);
    crate::carousel::script_mod(vm);
    crate::checkbox::script_mod(vm);
    crate::collapsible::script_mod(vm);
    crate::dialog::script_mod(vm);
    crate::drawer::script_mod(vm);
    crate::dropdown_menu::script_mod(vm);
    crate::hover_card::script_mod(vm);

    crate::skeleton::script_mod(vm);
    crate::kbd::script_mod(vm);
    crate::hr::script_mod(vm);
    crate::input::script_mod(vm);
    crate::label::script_mod(vm);
    crate::panel::script_mod(vm);
    crate::progress::script_mod(vm);
    crate::radio_group::script_mod(vm);
    crate::resizable::script_mod(vm);
    crate::select::script_mod(vm);
    crate::sheet::script_mod(vm);
    crate::scroll::script_mod(vm);
    crate::sidebar::script_mod(vm);
    crate::slider::script_mod(vm);
    crate::sonner::script_mod(vm);
    crate::spinner::script_mod(vm);
    crate::switch::script_mod(vm);
    crate::tabs::script_mod(vm);
    crate::tooltip::script_mod(vm);
}
