use crate::ui::page_macros::gallery_stateful_page_shell;
use makepad_components::makepad_widgets::*;

#[derive(Clone, Copy)]
struct IconGalleryEntry {
    row_index: usize,
    row_id: &'static str,
    card_id: &'static str,
    icon_name: &'static str,
    widget_name: &'static str,
}

macro_rules! icon_gallery_page_generated {
    ($($icon_rows:tt)*) => {
        gallery_stateful_page_shell! {
            widget: GalleryIconGalleryPage,
            page: icon_gallery_page,
            title: "Icons",
            subtitle: "Generated Lucide icon components from makepad-icon/resources/icons. Search by Lucide asset name or generated Rust widget name.",
            divider: { ShadHr{} },
            preview_spacing: 12.0,
            preview: {
                search_toolbar := View{
                    width: Fill
                    height: Fit
                    flow: Right
                    spacing: 8.0

                    search_field := ShadInputWithIcon{
                        width: Fill
                        input +: {
                            empty_text: "Search icons or widget names..."
                        }
                    }

                    icon_search_btn := ShadButtonSm{text: "Search"}
                }

                icon_results_summary := ShadFieldDescription{
                    text: "Showing all generated icons."
                }

                usage_card := ShadSurfaceMuted{
                    width: Fill
                    height: Fit
                    flow: Down
                    spacing: 8.0
                    padding: Inset{left: 14, right: 14, top: 14, bottom: 14}
                    draw_bg +: {
                        border_size: 1.0
                        border_color: (shad_theme.color_outline_border)
                    }

                    icon_usage_title := ShadSectionHeader{
                        text: "Using IconSearch"
                    }

                    icon_usage_description := ShadFieldDescription{
                        text: "Use the generated widget name directly in script_mod!. The snippet updates to the first visible search match."
                    }

                    icon_usage_snippet := mod.widgets.GalleryCodeSnippet{
                        code: "IconSearch{\n    icon_walk: Walk{width: 18, height: 18}\n    draw_icon.color: (shad_theme.color_primary)\n}\n"
                    }
                }

                icon_grid := View{
                    width: Fill
                    height: Fit
                    flow: Down
                    spacing: 10.0

                    $($icon_rows)*
                }
            },
            action_flow: {
                mod.widgets.GalleryActionFlowStep{text: "1. Run `python3 makepad-icon/scripts/download_lucide_icons.py --clean` to refresh SVG assets from Lucide."}
                mod.widgets.GalleryActionFlowStep{text: "2. Build `makepad-icon` or `makepad-gallery`; build.rs scans icons and regenerates both the preview grid and the search metadata automatically."}
                mod.widgets.GalleryActionFlowStep{text: "3. Search by Lucide asset name like `search` or by Rust widget name like `IconSearch` to narrow the grid quickly."}
                mod.widgets.GalleryActionFlowStep{text: "4. Use the widget name shown on each tile directly in script_mod!, and start from the usage snippet panel when you need sizing or color overrides."}
            },
        }
    };
}

// Generated by makepad-gallery/build.rs. Do not edit manually.
include!(concat!(env!("OUT_DIR"), "/icon_preview_rows.rs"));

#[derive(Script, Widget)]
pub struct GalleryIconGalleryPage {
    #[source]
    source: ScriptObjectRef,
    #[deref]
    view: View,
    #[rust]
    query: String,
}

impl GalleryIconGalleryPage {
    fn default_entry() -> &'static IconGalleryEntry {
        ICON_GALLERY_ENTRIES
            .iter()
            .find(|entry| entry.widget_name == "IconSearch")
            .unwrap_or(&ICON_GALLERY_ENTRIES[0])
    }

    fn normalize_query(query: &str) -> String {
        query.trim().to_ascii_lowercase()
    }

    fn summary_text(query: &str, matches_count: usize) -> String {
        if query.is_empty() {
            format!("Showing all {ICON_GALLERY_TOTAL} generated icons.")
        } else if matches_count == 0 {
            format!("No icons matched \"{query}\".")
        } else {
            format!(
                "Showing {matches_count} of {ICON_GALLERY_TOTAL} icons for \"{query}\"."
            )
        }
    }

    fn usage_code(widget_name: &str) -> String {
        format!(
            "{widget_name}{{\n    icon_walk: Walk{{width: 18, height: 18}}\n    draw_icon.color: (shad_theme.color_primary)\n}}\n"
        )
    }

    fn sync_usage_preview(&self, cx: &mut Cx, entry: &IconGalleryEntry) {
        self.view
            .label(cx, ids!(icon_usage_title))
            .set_text(cx, &format!("Using {}", entry.widget_name));
        self.view
            .label(cx, ids!(icon_usage_description))
            .set_text(
                cx,
                &format!(
                    "Lucide asset \"{}\" generates the `{}` widget. Drop it into script_mod! and override icon_walk or draw_icon.color as needed.",
                    entry.icon_name, entry.widget_name
                ),
            );
        self.view
            .widget(cx, ids!(icon_usage_snippet.container.code_view))
            .set_text(cx, &Self::usage_code(entry.widget_name));
    }

    fn apply_filter(&mut self, cx: &mut Cx) {
        let display_query = self.query.trim().to_string();
        let query = Self::normalize_query(&self.query);
        let mut visible_rows = vec![false; ICON_GALLERY_ROW_IDS.len()];
        let mut matches_count = 0;
        let mut first_match = None;

        for entry in ICON_GALLERY_ENTRIES {
            let matches = query.is_empty()
                || entry.icon_name.contains(&query)
                || entry.widget_name.to_ascii_lowercase().contains(&query);
            if matches {
                visible_rows[entry.row_index] = true;
                matches_count += 1;
                if first_match.is_none() {
                    first_match = Some(entry);
                }
            }

            self.view
                .widget(
                    cx,
                    &[
                        live_id!(icon_grid),
                        LiveId::from_str(entry.row_id),
                        LiveId::from_str(entry.card_id),
                    ],
                )
                .set_visible(cx, matches);
        }

        for (row_index, row_id) in ICON_GALLERY_ROW_IDS.iter().enumerate() {
            self.view
                .widget(cx, &[live_id!(icon_grid), LiveId::from_str(row_id)])
                .set_visible(cx, visible_rows[row_index]);
        }

        self.view
            .label(cx, ids!(icon_results_summary))
            .set_text(cx, &Self::summary_text(&display_query, matches_count));
        self.sync_usage_preview(
            cx,
            if query.is_empty() {
                Self::default_entry()
            } else {
                first_match.unwrap_or(Self::default_entry())
            },
        );
        self.view.redraw(cx);
    }
}

impl ScriptHook for GalleryIconGalleryPage {
    fn on_after_apply(
        &mut self,
        vm: &mut ScriptVm,
        _apply: &Apply,
        _scope: &mut Scope,
        _value: ScriptValue,
    ) {
        vm.with_cx_mut(|cx| {
            self.apply_filter(cx);
        });
    }
}

impl Widget for GalleryIconGalleryPage {
    fn handle_event(&mut self, cx: &mut Cx, event: &Event, scope: &mut Scope) {
        self.view.handle_event(cx, event, scope);

        if let Event::Actions(actions) = event {
            let search_input = self.view.text_input(cx, ids!(search_field.input));
            let mut next_query = None;

            if let Some(text) = search_input.changed(actions) {
                next_query = Some(text);
            }
            if let Some((text, _modifiers)) = search_input.returned(actions) {
                next_query = Some(text);
            }
            if self.view.button(cx, ids!(icon_search_btn)).clicked(actions) {
                search_input.set_key_focus(cx);
                next_query = Some(search_input.text());
            }

            if let Some(query) = next_query {
                self.query = query;
                self.apply_filter(cx);
            }
        }
    }

    fn draw_walk(&mut self, cx: &mut Cx2d, scope: &mut Scope, walk: Walk) -> DrawStep {
        self.view.draw_walk(cx, scope, walk)
    }
}
