use crate::ui::page_macros::gallery_stateful_page_shell;
use makepad_components::makepad_widgets::*;

const ICON_ROW_HEIGHT: f64 = 72.0;

#[derive(Clone, Copy)]
struct IconGalleryEntry {
    icon_name: &'static str,
    widget_name: &'static str,
    resource_path: &'static str,
}

gallery_stateful_page_shell! {
    widget: GalleryIconGalleryPage,
    page: icon_gallery_page,
    title: "Icons",
    subtitle: "Generated Lucide icon components from makepad-icon/resources/icons. Search by Lucide asset name or generated Rust widget name.",
    divider: { ShadHr{} },
    preview_spacing: 12.0,
    preview: {
        search_toolbar := View{
            width: Fill
            height: Fit
            flow: Right
            spacing: 8.0

            search_field := ShadInputWithIcon{
                width: Fill
                input +: {
                    empty_text: "Search icons or widget names..."
                }
            }

            clear_search_btn := ShadButtonOutline{
                text: "Clear"
                visible: false
            }

            icon_search_btn := ShadButtonSm{text: "Search"}
        }

        icon_results_summary := ShadFieldDescription{
            text: "Showing all generated icons."
        }

        usage_card := ShadSurfaceMuted{
            width: Fill
            height: Fit
            flow: Down
            spacing: 8.0
            padding: Inset{left: 14, right: 14, top: 14, bottom: 14}
            draw_bg +: {
                border_size: 1.0
                border_color: (shad_theme.color_outline_border)
            }

            icon_usage_title := ShadSectionHeader{
                text: "Using IconSearch"
            }

            icon_usage_description := ShadFieldDescription{
                text: "Use the generated widget name directly in script_mod!. The snippet updates to the first visible search match."
            }

            icon_usage_snippet := mod.widgets.GalleryCodeSnippet{
                code: "IconSearch{\n    icon_walk: Walk{width: 18, height: 18}\n    draw_icon.color: (shad_theme.color_primary)\n}\n"
            }
        }

        icon_list := PortalList{
            width: Fill
            height: 420.0
            flow: Down
            max_pull_down: 0.0
            capture_overload: true
            grab_key_focus: false
            auto_tail: false
            selectable: false
            drag_scrolling: true

            Empty := mod.widgets.ShadTableEmptyRow{}

            Item := RoundedView{
                width: Fill
                height: 72
                flow: Right
                spacing: 12.0
                align: Align{x: 0.0 y: 0.5}
                padding: Inset{left: 12, right: 12, top: 0, bottom: 0}
                draw_bg +: {
                    color: (shad_theme.color_secondary)
                    border_size: 1.0
                    border_radius: (shad_theme.radius)
                    border_color: (shad_theme.color_outline_border)
                }

                preview := RoundedView{
                    width: 40
                    height: 40
                    align: Align{x: 0.5 y: 0.5}
                    draw_bg +: {
                        color: (shad_theme.color_muted)
                        border_radius: 10.0
                    }

                    icon := Icon{
                        icon_walk: Walk{width: 18, height: 18}
                        draw_icon.color: (shad_theme.color_primary)
                    }
                }

                copy := View{
                    width: Fill
                    height: Fit
                    flow: Down
                    spacing: 4.0

                    icon_name := ShadLabel{
                        text: ""
                        draw_text.text_style.font_size: 12
                    }

                    widget_name := ShadFieldDescription{
                        width: Fill
                        text: ""
                        draw_text.text_style.font_size: 11
                    }
                }
            }
        }
    },
    action_flow: {
        mod.widgets.GalleryActionFlowStep{text: "1. Run `python3 makepad-icon/scripts/download_lucide_icons.py --clean` to refresh SVG assets from Lucide."}
        mod.widgets.GalleryActionFlowStep{text: "2. Build `makepad-icon` or `makepad-gallery`; build.rs scans icons and regenerates the gallery metadata automatically."}
        mod.widgets.GalleryActionFlowStep{text: "3. Search by Lucide asset name like `search` or by Rust widget name like `IconSearch` to narrow the virtualized list quickly."}
        mod.widgets.GalleryActionFlowStep{text: "4. Use the widget name shown on each tile directly in script_mod!, and start from the usage snippet panel when you need sizing or color overrides."}
    },
}

// Generated by makepad-gallery/build.rs. Do not edit manually.
include!(concat!(env!("OUT_DIR"), "/icon_preview_rows.rs"));

#[derive(Script, Widget)]
pub struct GalleryIconGalleryPage {
    #[source]
    source: ScriptObjectRef,
    #[deref]
    view: View,
    #[rust]
    query: String,
    #[rust]
    widget_name_lower: Vec<String>,
    #[rust]
    filtered_entry_indices: Vec<usize>,
    #[rust]
    filtered_entry_indices_scratch: Vec<usize>,
    #[rust]
    summary_cache: String,
    #[rust]
    usage_entry_cache: Option<usize>,
}

impl GalleryIconGalleryPage {
    fn normalize_query(query: &str) -> String {
        query.trim().to_ascii_lowercase()
    }

    fn summary_text(query: &str, matches_count: usize) -> String {
        if query.is_empty() {
            format!("Showing all {ICON_GALLERY_TOTAL} generated icons.")
        } else if matches_count == 0 {
            format!("No icons matched \"{query}\".")
        } else {
            format!(
                "Showing {matches_count} of {ICON_GALLERY_TOTAL} icons for \"{query}\"."
            )
        }
    }

    fn usage_code(widget_name: &str) -> String {
        format!(
            "{widget_name}{{\n    icon_walk: Walk{{width: 18, height: 18}}\n    draw_icon.color: (shad_theme.color_primary)\n}}\n"
        )
    }

    fn sync_empty_usage_preview(&self, cx: &mut Cx, query: &str) {
        self.view
            .label(cx, ids!(icon_usage_title))
            .set_text(cx, "No matching icon");
        self.view
            .label(cx, ids!(icon_usage_description))
            .set_text(
                cx,
                &format!(
                    "No generated icon matched \"{query}\". Clear or broaden the search to restore the usage snippet."
                ),
            );
        self.view
            .widget(cx, ids!(icon_usage_snippet.container.code_view))
            .set_text(
                cx,
                "// No icon snippet available while the current search has no matches.\n",
            );
    }

    fn sync_usage_preview(&self, cx: &mut Cx, entry: &IconGalleryEntry) {
        self.view
            .label(cx, ids!(icon_usage_title))
            .set_text(cx, &format!("Using {}", entry.widget_name));
        self.view
            .label(cx, ids!(icon_usage_description))
            .set_text(
                cx,
                &format!(
                    "Lucide asset \"{}\" generates the `{}` widget. Drop it into script_mod! and override icon_walk or draw_icon.color as needed.",
                    entry.icon_name, entry.widget_name
                ),
            );
        self.view
            .widget(cx, ids!(icon_usage_snippet.container.code_view))
            .set_text(cx, &Self::usage_code(entry.widget_name));
    }

    fn ensure_filter_cache(&mut self) {
        if self.widget_name_lower.len() == ICON_GALLERY_ENTRIES.len() {
            return;
        }

        self.widget_name_lower = ICON_GALLERY_ENTRIES
            .iter()
            .map(|entry| entry.widget_name.to_ascii_lowercase())
            .collect();
        self.filtered_entry_indices.clear();
        self.filtered_entry_indices_scratch.clear();
    }

    fn apply_filter(&mut self, cx: &mut Cx) {
        self.ensure_filter_cache();
        let display_query = self.query.trim().to_string();
        let query = Self::normalize_query(&self.query);
        let mut matches_count = 0;
        let mut first_match_index = None;
        let mut changed = false;
        self.filtered_entry_indices_scratch.clear();

        for (index, entry) in ICON_GALLERY_ENTRIES.iter().enumerate() {
            let matches = query.is_empty()
                || entry.icon_name.contains(&query)
                || self.widget_name_lower[index].contains(&query);
            if matches {
                self.filtered_entry_indices_scratch.push(index);
                matches_count += 1;
                if first_match_index.is_none() {
                    first_match_index = Some(index);
                }
            }
        }

        if self.filtered_entry_indices != self.filtered_entry_indices_scratch {
            std::mem::swap(
                &mut self.filtered_entry_indices,
                &mut self.filtered_entry_indices_scratch,
            );
            changed = true;
        }

        let summary = Self::summary_text(&display_query, matches_count);
        if self.summary_cache != summary {
            self.summary_cache = summary;
            self.view
                .label(cx, ids!(icon_results_summary))
                .set_text(cx, &self.summary_cache);
            changed = true;
        }

        self.view
            .button(cx, ids!(clear_search_btn))
            .set_visible(cx, !query.is_empty());

        match first_match_index {
            Some(target_entry_index) => {
                if self.usage_entry_cache != Some(target_entry_index) {
                    self.usage_entry_cache = Some(target_entry_index);
                    self.sync_usage_preview(cx, &ICON_GALLERY_ENTRIES[target_entry_index]);
                    changed = true;
                }
            }
            None => {
                if self.usage_entry_cache.is_some() || !query.is_empty() {
                    self.usage_entry_cache = None;
                    self.sync_empty_usage_preview(cx, &display_query);
                    changed = true;
                }
            }
        }

        if changed {
            self.view.redraw(cx);
        }
    }

    fn empty_fill_rows(list: &PortalList, cx: &Cx2d, used_rows: usize) -> usize {
        ((list.area().rect(cx).size.y.max(0.0) / ICON_ROW_HEIGHT).ceil() as usize)
            .saturating_sub(used_rows)
    }

    fn bind_icon_item(&self, cx: &mut Cx2d, item: &WidgetRef, entry: &IconGalleryEntry) {
        item.label(cx, ids!(copy.icon_name))
            .set_text(cx, entry.icon_name);
        item.label(cx, ids!(copy.widget_name))
            .set_text(cx, entry.widget_name);

        let mut icon = item.widget(cx, ids!(preview.icon));
        let resource_path = entry.resource_path;
        script_apply_eval!(cx, icon, {
            draw_icon: {
                svg: res.crate_resource(#(resource_path))
            }
        });
    }

    fn draw_empty_rows(&self, cx: &mut Cx2d, list: &mut PortalList, label: &str) {
        let rows = Self::empty_fill_rows(list, cx, 0).max(1);
        list.set_item_range(cx, 0, rows);
        while let Some(item_id) = list.next_visible_item(cx) {
            let item = list.item(cx, item_id, id!(Empty)).as_view();
            item.label(cx, ids!(empty_label))
                .set_text(cx, if item_id == 0 { label } else { "" });
            item.draw_all(cx, &mut Scope::empty());
        }
    }

    fn draw_icon_rows(&self, cx: &mut Cx2d, list: &mut PortalList) {
        if self.filtered_entry_indices.is_empty() {
            self.draw_empty_rows(cx, list, "No icons matched the current search.");
            return;
        }

        let row_count = self.filtered_entry_indices.len();
        let empty_rows = Self::empty_fill_rows(list, cx, row_count);
        list.set_item_range(cx, 0, row_count + empty_rows);

        while let Some(item_id) = list.next_visible_item(cx) {
            if item_id >= row_count {
                let item = list.item(cx, item_id, id!(Empty)).as_view();
                item.label(cx, ids!(empty_label)).set_text(cx, "");
                item.draw_all(cx, &mut Scope::empty());
                continue;
            }

            let entry = &ICON_GALLERY_ENTRIES[self.filtered_entry_indices[item_id]];
            let item = list.item(cx, item_id, id!(Item));
            self.bind_icon_item(cx, &item, entry);
            item.draw_all(cx, &mut Scope::empty());
        }
    }
}

impl ScriptHook for GalleryIconGalleryPage {
    fn on_after_apply(
        &mut self,
        vm: &mut ScriptVm,
        _apply: &Apply,
        _scope: &mut Scope,
        _value: ScriptValue,
    ) {
        vm.with_cx_mut(|cx| {
            self.apply_filter(cx);
        });
    }
}

impl Widget for GalleryIconGalleryPage {
    fn handle_event(&mut self, cx: &mut Cx, event: &Event, scope: &mut Scope) {
        self.view.handle_event(cx, event, scope);

        if let Event::Actions(actions) = event {
            let search_input = self.view.text_input(cx, ids!(search_field.input));
            let mut next_query = None;

            if let Some(text) = search_input.changed(actions) {
                next_query = Some(text);
            }
            if let Some((text, _modifiers)) = search_input.returned(actions) {
                next_query = Some(text);
            }
            if self.view.button(cx, ids!(icon_search_btn)).clicked(actions) {
                search_input.set_key_focus(cx);
                next_query = Some(search_input.text());
            }
            if self.view.button(cx, ids!(clear_search_btn)).clicked(actions) {
                search_input.set_text(cx, "");
                search_input.set_key_focus(cx);
                next_query = Some(String::new());
            }

            if let Some(query) = next_query {
                self.query = query;
                self.apply_filter(cx);
            }
        }
    }

    fn draw_walk(&mut self, cx: &mut Cx2d, scope: &mut Scope, walk: Walk) -> DrawStep {
        while let Some(step) = self.view.draw_walk(cx, scope, walk).step() {
            if let Some(mut list) = step.as_portal_list().borrow_mut() {
                self.draw_icon_rows(cx, &mut list);
            }
        }
        DrawStep::done()
    }
}
