macro_rules! gallery_page_entries {
    ($callback:ident) => {
        $callback! {
            {
                title: "Accordion",
                route: "/",
                page: accordion_page,
                widget: GalleryAccordionPage,
                sidebar_id: sidebar_accordion,
                sidebar_label: "Accordion",
                section: "Components",
                shortcut: "A",
                snippet: Accordion,
                transition: none,
            }
            {
                title: "Alert",
                route: "/alert",
                page: alert_page,
                widget: GalleryAlertPage,
                sidebar_id: sidebar_alert,
                sidebar_label: "Alert",
                section: "Feedback",
                shortcut: "L",
                snippet: Alert,
            }
            {
                title: "Aspect Ratio",
                route: "/aspect-ratio",
                page: aspect_ratio_page,
                widget: GalleryAspectRatioPage,
                sidebar_id: sidebar_aspect_ratio,
                sidebar_label: "Aspect Ratio",
                section: "Layout",
                shortcut: "R",
                snippet: AspectRatio,
            }
            {
                title: "Avatar",
                route: "/avatar",
                page: avatar_page,
                widget: GalleryAvatarPage,
                sidebar_id: sidebar_avatar,
                sidebar_label: "Avatar",
                section: "Components",
                shortcut: "V",
                snippet: Avatar,
            }
            {
                title: "Badge",
                route: "/badge",
                page: badge_page,
                widget: GalleryBadgePage,
                sidebar_id: sidebar_badge,
                sidebar_label: "Badge",
                section: "Components",
                shortcut: "B",
                snippet: Badge,
            }
            {
                title: "Breadcrumb",
                route: "/breadcrumb",
                page: breadcrumb_page,
                widget: GalleryBreadcrumbPage,
                sidebar_id: sidebar_breadcrumb,
                sidebar_label: "Breadcrumb",
                section: "Navigation",
                shortcut: "C",
                snippet: Breadcrumb,
            }
            {
                title: "Button",
                route: "/button",
                page: button_page,
                widget: GalleryButtonPage,
                sidebar_id: sidebar_button,
                sidebar_label: "Button",
                section: "Components",
                shortcut: "U",
                snippet: Button,
            }
            {
                title: "Button Group",
                route: "/button-group",
                page: button_group_page,
                widget: GalleryButtonGroupPage,
                sidebar_id: sidebar_button_group,
                sidebar_label: "Button Group",
                section: "Components",
                shortcut: "G",
                snippet: ButtonGroup,
            }
            {
                title: "Calendar",
                route: "/calendar",
                page: calendar_page,
                widget: GalleryCalendarPage,
                sidebar_id: sidebar_calendar,
                sidebar_label: "Calendar",
                section: "Forms",
                shortcut: "7",
                snippet: Calendar,
            }
            {
                title: "Card",
                route: "/card",
                page: card_page,
                widget: GalleryCardPage,
                sidebar_id: sidebar_card,
                sidebar_label: "Card",
                section: "Components",
                shortcut: "D",
                snippet: Card,
            }
            {
                title: "Carousel",
                route: "/carousel",
                page: carousel_page,
                widget: GalleryCarouselPage,
                sidebar_id: sidebar_carousel,
                sidebar_label: "Carousel",
                section: "Components",
                shortcut: "O",
                snippet: Carousel,
            }
            {
                title: "Chart",
                route: "/chart",
                page: chart_page,
                widget: GalleryChartPage,
                sidebar_id: sidebar_chart,
                sidebar_label: "Chart",
                section: "Data",
                shortcut: "H",
                snippet: Chart,
            }
            {
                title: "Checkbox",
                route: "/checkbox",
                page: checkbox_page,
                widget: GalleryCheckboxPage,
                sidebar_id: sidebar_checkbox,
                sidebar_label: "Checkbox",
                section: "Forms",
                shortcut: "X",
                snippet: Checkbox,
            }
            {
                title: "Collapsible",
                route: "/collapsible",
                page: collapsible_page,
                widget: GalleryCollapsiblePage,
                sidebar_id: sidebar_collapsible,
                sidebar_label: "Collapsible",
                section: "Components",
                shortcut: "P",
                snippet: Collapsible,
            }
            {
                title: "Command Palette",
                route: "/command-palette",
                page: command_palette_page,
                widget: GalleryCommandPalettePage,
                sidebar_id: sidebar_command_palette,
                sidebar_label: "Command Palette",
                section: "Navigation",
                shortcut: "K",
                snippet: CommandPalette,
            }
            {
                title: "Context Menu",
                route: "/context-menu",
                page: context_menu_page,
                widget: GalleryContextMenuPage,
                sidebar_id: sidebar_context_menu,
                sidebar_label: "Context Menu",
                section: "Overlays",
                shortcut: "X1",
                snippet: ContextMenu,
            }
            {
                title: "Date Picker",
                route: "/date-picker",
                page: date_picker_page,
                widget: GalleryDatePickerPage,
                sidebar_id: sidebar_date_picker,
                sidebar_label: "Date Picker",
                section: "Forms",
                shortcut: "5",
                snippet: DatePicker,
            }
            {
                title: "Dialog",
                route: "/dialog",
                page: dialog_page,
                widget: GalleryDialogPage,
                sidebar_id: sidebar_dialog,
                sidebar_label: "Dialog",
                section: "Overlays",
                shortcut: "I",
                snippet: Dialog,
            }
            {
                title: "Input",
                route: "/input",
                page: input_page,
                widget: GalleryInputPage,
                sidebar_id: sidebar_input,
                sidebar_label: "Input",
                section: "Forms",
                shortcut: "N",
                snippet: Input,
            }
            {
                title: "Input OTP",
                route: "/input-otp",
                page: input_otp_page,
                widget: GalleryInputOtpPage,
                sidebar_id: sidebar_input_otp,
                sidebar_label: "Input OTP",
                section: "Forms",
                shortcut: "6",
                snippet: InputOtp,
            }
            {
                title: "Kbd",
                route: "/kbd",
                page: kbd_page,
                widget: GalleryKbdPage,
                sidebar_id: sidebar_kbd,
                sidebar_label: "Kbd",
                section: "Forms",
                shortcut: "KB",
                snippet: Kbd,
            }
            {
                title: "Label",
                route: "/label",
                page: label_page,
                widget: GalleryLabelPage,
                sidebar_id: sidebar_label,
                sidebar_label: "Label",
                section: "Forms",
                shortcut: "LB",
                snippet: Label,
            }
            {
                title: "Menubar",
                route: "/menubar",
                page: menubar_page,
                widget: GalleryMenubarPage,
                sidebar_id: sidebar_menubar,
                sidebar_label: "Menubar",
                section: "Navigation",
                shortcut: "MB",
                snippet: Menubar,
            }
            {
                title: "Navigation Menu",
                route: "/navigation-menu",
                page: navigation_menu_page,
                widget: GalleryNavigationMenuPage,
                sidebar_id: sidebar_navigation_menu,
                sidebar_label: "Navigation Menu",
                section: "Navigation",
                shortcut: "NM",
                snippet: NavigationMenu,
            }
            {
                title: "Pagination",
                route: "/pagination",
                page: pagination_page,
                widget: GalleryPaginationPage,
                sidebar_id: sidebar_pagination,
                sidebar_label: "Pagination",
                section: "Navigation",
                shortcut: "PG",
                snippet: Pagination,
            }
            {
                title: "Popover",
                route: "/popover",
                page: popover_page,
                widget: GalleryPopoverPage,
                sidebar_id: sidebar_popover,
                sidebar_label: "Popover",
                section: "Overlays",
                shortcut: "PO",
                snippet: Popover,
            }
            {
                title: "Progress",
                route: "/progress",
                page: progress_page,
                widget: GalleryProgressPage,
                sidebar_id: sidebar_progress,
                sidebar_label: "Progress",
                section: "Feedback",
                shortcut: "PR",
                snippet: Progress,
            }
            {
                title: "Radio Group",
                route: "/radio-group",
                page: radio_group_page,
                widget: GalleryRadioGroupPage,
                sidebar_id: sidebar_radio_group,
                sidebar_label: "Radio Group",
                section: "Forms",
                shortcut: "RG",
                snippet: RadioGroup,
            }
            {
                title: "Resizable",
                route: "/resizable",
                page: resizable_page,
                widget: GalleryResizablePage,
                sidebar_id: sidebar_resizable,
                sidebar_label: "Resizable",
                section: "Layout",
                shortcut: "Z",
                snippet: Resizable,
            }
            {
                title: "Scroll Area",
                route: "/scroll-area",
                page: scroll_area_page,
                widget: GalleryScrollAreaPage,
                sidebar_id: sidebar_scroll_area,
                sidebar_label: "Scroll Area",
                section: "Layout",
                shortcut: "SA",
                snippet: ScrollArea,
            }
            {
                title: "Select",
                route: "/select",
                page: select_page,
                widget: GallerySelectPage,
                sidebar_id: sidebar_select,
                sidebar_label: "Select",
                section: "Forms",
                shortcut: "E",
                snippet: Select,
            }
            {
                title: "Separator",
                route: "/separator",
                page: separator_page,
                widget: GallerySeparatorPage,
                sidebar_id: sidebar_separator,
                sidebar_label: "Separator",
                section: "Layout",
                shortcut: "SP",
                snippet: Separator,
            }
            {
                title: "Sheet",
                route: "/sheet",
                page: sheet_page,
                widget: GallerySheetPage,
                sidebar_id: sidebar_sheet,
                sidebar_label: "Sheet",
                section: "Overlays",
                shortcut: "SH",
                snippet: Sheet,
            }
            {
                title: "Sidebar",
                route: "/sidebar",
                page: sidebar_page,
                widget: GallerySidebarPage,
                sidebar_id: sidebar_sidebar,
                sidebar_label: "Sidebar",
                section: "Navigation",
                shortcut: "SB",
                snippet: Sidebar,
            }
            {
                title: "Skeleton",
                route: "/skeleton",
                page: skeleton_page,
                widget: GallerySkeletonPage,
                sidebar_id: sidebar_skeleton,
                sidebar_label: "Skeleton",
                section: "Feedback",
                shortcut: "SK",
                snippet: Skeleton,
            }
            {
                title: "Slider",
                route: "/slider",
                page: slider_page,
                widget: GallerySliderPage,
                sidebar_id: sidebar_slider,
                sidebar_label: "Slider",
                section: "Forms",
                shortcut: "J",
                snippet: Slider,
            }
            {
                title: "Sonner",
                route: "/sonner",
                page: sonner_page,
                widget: GallerySonnerPage,
                sidebar_id: sidebar_sonner,
                sidebar_label: "Sonner",
                section: "Feedback",
                shortcut: "SN",
                snippet: Sonner,
            }
            {
                title: "Spinner",
                route: "/spinner",
                page: spinner_page,
                widget: GallerySpinnerPage,
                sidebar_id: sidebar_spinner,
                sidebar_label: "Spinner",
                section: "Feedback",
                shortcut: "W",
                snippet: Spinner,
            }
            {
                title: "Switch",
                route: "/switch",
                page: switch_page,
                widget: GallerySwitchPage,
                sidebar_id: sidebar_switch,
                sidebar_label: "Switch",
                section: "Forms",
                shortcut: "SW",
                snippet: Switch,
            }
            {
                title: "Table",
                route: "/table",
                page: table_page,
                widget: GalleryTablePage,
                sidebar_id: sidebar_table,
                sidebar_label: "Table",
                section: "Data",
                shortcut: "8",
                snippet: Table,
            }
            {
                title: "Tabs",
                route: "/tabs",
                page: tabs_page,
                widget: GalleryTabsPage,
                sidebar_id: sidebar_tabs,
                sidebar_label: "Tabs",
                section: "Navigation",
                shortcut: "TB",
                snippet: Tabs,
            }
            {
                title: "Textarea",
                route: "/textarea",
                page: textarea_page,
                widget: GalleryTextareaPage,
                sidebar_id: sidebar_textarea,
                sidebar_label: "Textarea",
                section: "Forms",
                shortcut: "TA",
                snippet: Textarea,
            }
            {
                title: "Toggle",
                route: "/toggle",
                page: toggle_page,
                widget: GalleryTogglePage,
                sidebar_id: sidebar_toggle,
                sidebar_label: "Toggle",
                section: "Forms",
                shortcut: "TG",
                snippet: Toggle,
            }
        }
    };
}

pub(crate) use gallery_page_entries;
