macro_rules! gallery_page_entries {
    ($callback:ident $(, $args:tt)*) => {
        $callback! {
            $($args,)*
            {
                title: "Accordion",
                route: "/",
                page: accordion_page,
                widget: GalleryAccordionPage,
                sidebar_id: sidebar_accordion,
                sidebar_label: "Accordion",
                section: "Components",
                shortcut: "A",
                snippet: Accordion,
                bundle: base,
                components: [Accordion, Checkbox, Hr, Input, Label, Scroll, Switch],
                icons: [],
                icon_policy: none,
                transition: none,
            }
            {
                title: "Alert",
                route: "/alert",
                page: alert_page,
                widget: GalleryAlertPage,
                sidebar_id: sidebar_alert,
                sidebar_label: "Alert",
                section: "Feedback",
                shortcut: "L",
                snippet: Alert,
                bundle: page,
                components: [Alert, Hr, Input, Label, Scroll],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Aspect Ratio",
                route: "/aspect-ratio",
                page: aspect_ratio_page,
                widget: GalleryAspectRatioPage,
                sidebar_id: sidebar_aspect_ratio,
                sidebar_label: "Aspect Ratio",
                section: "Layout",
                shortcut: "R",
                snippet: AspectRatio,
                bundle: page,
                components: [AspectRatio, Hr, Image, Input, Label, Scroll, Surface],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Avatar",
                route: "/avatar",
                page: avatar_page,
                widget: GalleryAvatarPage,
                sidebar_id: sidebar_avatar,
                sidebar_label: "Avatar",
                section: "Components",
                shortcut: "V",
                snippet: Avatar,
                bundle: page,
                components: [Avatar, Hr, Input, Label, Scroll],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Badge",
                route: "/badge",
                page: badge_page,
                widget: GalleryBadgePage,
                sidebar_id: sidebar_badge,
                sidebar_label: "Badge",
                section: "Components",
                shortcut: "B",
                snippet: Badge,
                bundle: page,
                components: [Badge, Hr, Input, Label, Scroll, Surface],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Breadcrumb",
                route: "/breadcrumb",
                page: breadcrumb_page,
                widget: GalleryBreadcrumbPage,
                sidebar_id: sidebar_breadcrumb,
                sidebar_label: "Breadcrumb",
                section: "Navigation",
                shortcut: "C",
                snippet: Breadcrumb,
                bundle: page,
                components: [Breadcrumb, Hr, Input, Label, Scroll, Surface],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Button",
                route: "/button",
                page: button_page,
                widget: GalleryButtonPage,
                sidebar_id: sidebar_button,
                sidebar_label: "Button",
                section: "Components",
                shortcut: "U",
                snippet: Button,
                bundle: page,
                components: [Alert, Button, Hr, Input, Label, Scroll],
                icons: [
                    ButtonChevronLeft,
                    ButtonChevronRight,
                    ButtonX,
                    ChevronDown,
                    ChevronLeft,
                    ChevronRight,
                    Check,
                    Info,
                    Search,
                    X,
                ],
                icon_policy: none,
            }
            {
                title: "Button Group",
                route: "/button-group",
                page: button_group_page,
                widget: GalleryButtonGroupPage,
                sidebar_id: sidebar_button_group,
                sidebar_label: "Button Group",
                section: "Components",
                shortcut: "G",
                snippet: ButtonGroup,
                bundle: page,
                components: [ButtonGroup, Hr, Label, Scroll],
                icons: [ButtonChevronLeft, ButtonMoreHorizontal],
                icon_policy: none,
            }
            {
                title: "Calendar",
                route: "/calendar",
                page: calendar_page,
                widget: GalleryCalendarPage,
                sidebar_id: sidebar_calendar,
                sidebar_label: "Calendar",
                section: "Forms",
                shortcut: "7",
                snippet: Calendar,
                bundle: page,
                components: [Button, Calendar, Hr, Input, Label, Scroll],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Card",
                route: "/card",
                page: card_page,
                widget: GalleryCardPage,
                sidebar_id: sidebar_card,
                sidebar_label: "Card",
                section: "Components",
                shortcut: "D",
                snippet: Card,
                bundle: page,
                components: [Badge, Button, Card, Hr, Input, Label, Scroll],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Carousel",
                route: "/carousel",
                page: carousel_page,
                widget: GalleryCarouselPage,
                sidebar_id: sidebar_carousel,
                sidebar_label: "Carousel",
                section: "Components",
                shortcut: "O",
                snippet: Carousel,
                bundle: page,
                components: [Carousel, Hr, Input, Label, Scroll],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Chart",
                route: "/chart",
                page: chart_page,
                widget: GalleryChartPage,
                sidebar_id: sidebar_chart,
                sidebar_label: "Chart",
                section: "Data",
                shortcut: "H",
                snippet: Chart,
                bundle: page,
                components: [Button, Chart, Hr, Input, Label, Scroll],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Checkbox",
                route: "/checkbox",
                page: checkbox_page,
                widget: GalleryCheckboxPage,
                sidebar_id: sidebar_checkbox,
                sidebar_label: "Checkbox",
                section: "Forms",
                shortcut: "X",
                snippet: Checkbox,
                bundle: page,
                components: [Checkbox, Hr, Label, Scroll],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Collapsible",
                route: "/collapsible",
                page: collapsible_page,
                widget: GalleryCollapsiblePage,
                sidebar_id: sidebar_collapsible,
                sidebar_label: "Collapsible",
                section: "Components",
                shortcut: "P",
                snippet: Collapsible,
                bundle: page,
                components: [Collapsible, Hr, Label, Scroll, Surface],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Command Palette",
                route: "/command-palette",
                page: command_palette_page,
                widget: GalleryCommandPalettePage,
                sidebar_id: sidebar_command_palette,
                sidebar_label: "Command Palette",
                section: "Navigation",
                shortcut: "K",
                snippet: CommandPalette,
                bundle: page,
                components: [Button, Hr, Input, Kbd, Label, Scroll, Surface],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Context Menu",
                route: "/context-menu",
                page: context_menu_page,
                widget: GalleryContextMenuPage,
                sidebar_id: sidebar_context_menu,
                sidebar_label: "Context Menu",
                section: "Overlays",
                shortcut: "X1",
                snippet: ContextMenu,
                bundle: page,
                components: [ContextMenu, Hr, Input, Label, Scroll, Surface],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Date Picker",
                route: "/date-picker",
                page: date_picker_page,
                widget: GalleryDatePickerPage,
                sidebar_id: sidebar_date_picker,
                sidebar_label: "Date Picker",
                section: "Forms",
                shortcut: "5",
                snippet: DatePicker,
                bundle: page,
                components: [Button, Calendar, DatePicker, Hr, Input, Label, Popover, Scroll],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Dialog",
                route: "/dialog",
                page: dialog_page,
                widget: GalleryDialogPage,
                sidebar_id: sidebar_dialog,
                sidebar_label: "Dialog",
                section: "Overlays",
                shortcut: "I",
                snippet: Dialog,
                bundle: page,
                components: [Button, Dialog, Hr, Input, Label, Panel, Scroll, Sheet],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Icons",
                route: "/icons",
                page: icon_gallery_page,
                widget: GalleryIconGalleryPage,
                sidebar_id: sidebar_icons,
                sidebar_label: "Icons",
                section: "Components",
                shortcut: "IC",
                snippet: IconGallery,
                bundle: page,
                components: [Button, Hr, Input, Label, Scroll, Surface, Table],
                icons: [],
                icon_policy: all,
            }
            {
                title: "Input",
                route: "/input",
                page: input_page,
                widget: GalleryInputPage,
                sidebar_id: sidebar_input,
                sidebar_label: "Input",
                section: "Forms",
                shortcut: "N",
                snippet: Input,
                bundle: page,
                components: [Hr, Input, Label, Scroll],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Input OTP",
                route: "/input-otp",
                page: input_otp_page,
                widget: GalleryInputOtpPage,
                sidebar_id: sidebar_input_otp,
                sidebar_label: "Input OTP",
                section: "Forms",
                shortcut: "6",
                snippet: InputOtp,
                bundle: page,
                components: [Hr, Input, InputOtp, Label, Scroll],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Kbd",
                route: "/kbd",
                page: kbd_page,
                widget: GalleryKbdPage,
                sidebar_id: sidebar_kbd,
                sidebar_label: "Kbd",
                section: "Forms",
                shortcut: "KB",
                snippet: Kbd,
                bundle: page,
                components: [Hr, Input, Kbd, Label, Scroll, Surface],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Label",
                route: "/label",
                page: label_page,
                widget: GalleryLabelPage,
                sidebar_id: sidebar_label,
                sidebar_label: "Label",
                section: "Forms",
                shortcut: "LB",
                snippet: Label,
                bundle: page,
                components: [Hr, Input, Label, Scroll, Surface],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Menubar",
                route: "/menubar",
                page: menubar_page,
                widget: GalleryMenubarPage,
                sidebar_id: sidebar_menubar,
                sidebar_label: "Menubar",
                section: "Navigation",
                shortcut: "MB",
                snippet: Menubar,
                bundle: page,
                components: [Hr, Input, Label, Menubar, Scroll],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Navigation Menu",
                route: "/navigation-menu",
                page: navigation_menu_page,
                widget: GalleryNavigationMenuPage,
                sidebar_id: sidebar_navigation_menu,
                sidebar_label: "Navigation Menu",
                section: "Navigation",
                shortcut: "NM",
                snippet: NavigationMenu,
                bundle: page,
                components: [Button, Hr, Input, Label, NavigationMenu, Scroll],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Pagination",
                route: "/pagination",
                page: pagination_page,
                widget: GalleryPaginationPage,
                sidebar_id: sidebar_pagination,
                sidebar_label: "Pagination",
                section: "Navigation",
                shortcut: "PG",
                snippet: Pagination,
                bundle: page,
                components: [Hr, Input, Label, Pagination, Scroll],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Popover",
                route: "/popover",
                page: popover_page,
                widget: GalleryPopoverPage,
                sidebar_id: sidebar_popover,
                sidebar_label: "Popover",
                section: "Overlays",
                shortcut: "PO",
                snippet: Popover,
                bundle: page,
                components: [Button, Hr, Input, Label, Popover, Scroll],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Progress",
                route: "/progress",
                page: progress_page,
                widget: GalleryProgressPage,
                sidebar_id: sidebar_progress,
                sidebar_label: "Progress",
                section: "Feedback",
                shortcut: "PR",
                snippet: Progress,
                bundle: page,
                components: [Hr, Label, Progress, Scroll],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Radio Group",
                route: "/radio-group",
                page: radio_group_page,
                widget: GalleryRadioGroupPage,
                sidebar_id: sidebar_radio_group,
                sidebar_label: "Radio Group",
                section: "Forms",
                shortcut: "RG",
                snippet: RadioGroup,
                bundle: page,
                components: [Hr, Label, Panel, RadioGroup, Scroll],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Resizable",
                route: "/resizable",
                page: resizable_page,
                widget: GalleryResizablePage,
                sidebar_id: sidebar_resizable,
                sidebar_label: "Resizable",
                section: "Layout",
                shortcut: "Z",
                snippet: Resizable,
                bundle: page,
                components: [Hr, Input, Label, Panel, Resizable, Scroll, Surface],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Scroll Area",
                route: "/scroll-area",
                page: scroll_area_page,
                widget: GalleryScrollAreaPage,
                sidebar_id: sidebar_scroll_area,
                sidebar_label: "Scroll Area",
                section: "Layout",
                shortcut: "SA",
                snippet: ScrollArea,
                bundle: page,
                components: [Badge, Hr, Label, Panel, Scroll],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Select",
                route: "/select",
                page: select_page,
                widget: GallerySelectPage,
                sidebar_id: sidebar_select,
                sidebar_label: "Select",
                section: "Forms",
                shortcut: "E",
                snippet: Select,
                bundle: page,
                components: [Hr, Input, Panel, Scroll, Select],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Separator",
                route: "/separator",
                page: separator_page,
                widget: GallerySeparatorPage,
                sidebar_id: sidebar_separator,
                sidebar_label: "Separator",
                section: "Layout",
                shortcut: "SP",
                snippet: Separator,
                bundle: page,
                components: [Hr, Input, Label, Panel, Scroll],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Sheet",
                route: "/sheet",
                page: sheet_page,
                widget: GallerySheetPage,
                sidebar_id: sidebar_sheet,
                sidebar_label: "Sheet",
                section: "Overlays",
                shortcut: "SH",
                snippet: Sheet,
                bundle: page,
                components: [Button, Hr, Input, Label, Scroll, Select, Sheet, Sidebar, Surface],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Sidebar",
                route: "/sidebar",
                page: sidebar_page,
                widget: GallerySidebarPage,
                sidebar_id: sidebar_sidebar,
                sidebar_label: "Sidebar",
                section: "Navigation",
                shortcut: "SB",
                snippet: Sidebar,
                bundle: page,
                components: [Hr, Label, Scroll, Sidebar],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Skeleton",
                route: "/skeleton",
                page: skeleton_page,
                widget: GallerySkeletonPage,
                sidebar_id: sidebar_skeleton,
                sidebar_label: "Skeleton",
                section: "Feedback",
                shortcut: "SK",
                snippet: Skeleton,
                bundle: page,
                components: [Hr, Input, Label, Scroll, Skeleton, Surface],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Slider",
                route: "/slider",
                page: slider_page,
                widget: GallerySliderPage,
                sidebar_id: sidebar_slider,
                sidebar_label: "Slider",
                section: "Forms",
                shortcut: "J",
                snippet: Slider,
                bundle: page,
                components: [Hr, Label, Scroll, Slider],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Sonner",
                route: "/sonner",
                page: sonner_page,
                widget: GallerySonnerPage,
                sidebar_id: sidebar_sonner,
                sidebar_label: "Sonner",
                section: "Feedback",
                shortcut: "SN",
                snippet: Sonner,
                bundle: page,
                components: [Button, Hr, Label, Scroll, Sonner],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Spinner",
                route: "/spinner",
                page: spinner_page,
                widget: GallerySpinnerPage,
                sidebar_id: sidebar_spinner,
                sidebar_label: "Spinner",
                section: "Feedback",
                shortcut: "W",
                snippet: Spinner,
                bundle: page,
                components: [Hr, Input, Label, Panel, Scroll, Spinner, Surface],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Switch",
                route: "/switch",
                page: switch_page,
                widget: GallerySwitchPage,
                sidebar_id: sidebar_switch,
                sidebar_label: "Switch",
                section: "Forms",
                shortcut: "SW",
                snippet: Switch,
                bundle: page,
                components: [Hr, Label, Scroll, Switch],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Table",
                route: "/table",
                page: table_page,
                widget: GalleryTablePage,
                sidebar_id: sidebar_table,
                sidebar_label: "Table",
                section: "Data",
                shortcut: "8",
                snippet: Table,
                bundle: page,
                components: [Button, Hr, Input, Label, Scroll, Table],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Tabs",
                route: "/tabs",
                page: tabs_page,
                widget: GalleryTabsPage,
                sidebar_id: sidebar_tabs,
                sidebar_label: "Tabs",
                section: "Navigation",
                shortcut: "TB",
                snippet: Tabs,
                bundle: page,
                components: [Hr, Input, Label, Scroll, Tabs],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Textarea",
                route: "/textarea",
                page: textarea_page,
                widget: GalleryTextareaPage,
                sidebar_id: sidebar_textarea,
                sidebar_label: "Textarea",
                section: "Forms",
                shortcut: "TA",
                snippet: Textarea,
                bundle: page,
                components: [Hr, Input, Label, Scroll, Textarea],
                icons: [],
                icon_policy: none,
            }
            {
                title: "Toggle",
                route: "/toggle",
                page: toggle_page,
                widget: GalleryTogglePage,
                sidebar_id: sidebar_toggle,
                sidebar_label: "Toggle",
                section: "Forms",
                shortcut: "TG",
                snippet: Toggle,
                bundle: page,
                components: [Hr, Label, Scroll, Toggle],
                icons: [],
                icon_policy: none,
            }
        }
    };
}

macro_rules! register_page_icons {
    (none, $vm:ident, [$($icons:ident),* $(,)?]) => {
        makepad_components::makepad_icon::register_icons(
            $vm,
            &[$(makepad_components::makepad_icon::IconModule::$icons),*],
        );
    };
    (all, $vm:ident, [$($icons:ident),* $(,)?]) => {
        makepad_components::makepad_icon::register_all_icons($vm);
    };
}

macro_rules! define_gallery_page_dependency_registrars {
    (
        $(
            {
                title: $title:literal,
                route: $route:literal,
                page: $page:ident,
                widget: $widget:ident,
                sidebar_id: $sidebar_id:ident,
                sidebar_label: $sidebar_label:literal,
                section: $section:literal,
                shortcut: $shortcut:literal,
                snippet: $snippet:ident,
                bundle: $bundle:ident,
                components: [$($components:ident),* $(,)?],
                icons: [$($icons:ident),* $(,)?],
                icon_policy: $icon_policy:ident,
                $(transition: $transition:ident,)?
            }
        )*
    ) => {
        $(
            pub(crate) mod $page {
                use makepad_components::makepad_widgets::*;

                pub(crate) fn register_bundle_dependencies(vm: &mut ScriptVm) {
                    makepad_components::register_component_set!(
                        vm,
                        [$($components),*]
                    );
                    register_page_icons!($icon_policy, vm, [$($icons),*]);
                }
            }
        )*
    };
}

gallery_page_entries!(define_gallery_page_dependency_registrars);

pub(crate) use gallery_page_entries;
