use std::ffi::OsStr;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

const GENERATED_BINDINGS_FILE: &str = "lucide_icon_bindings.rs";
const ICON_RESOURCE_PREFIX: &str = "self://resources/icons/";

fn to_widget_name(icon_stem: &str) -> Option<String> {
    let parts = icon_stem
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty());

    let mut widget = String::from("Icon");
    let mut has_part = false;
    for part in parts {
        has_part = true;
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            widget.push(first.to_ascii_uppercase());
            widget.extend(chars);
        }
    }
    has_part.then_some(widget)
}

fn icon_bindings(icons_dir: &Path) -> std::io::Result<String> {
    let mut entries: Vec<PathBuf> = fs::read_dir(icons_dir)?
        .filter_map(|entry| entry.ok().map(|value| value.path()))
        .filter(|path| path.extension().is_some_and(|ext| ext == OsStr::new("svg")))
        .collect();
    entries.sort();

    let mut output = String::from(
        "// Generated by makepad-icon/build.rs\n\
         // Do not edit manually.\n\
         define_lucide_icons! {\n",
    );
    for path in entries {
        println!("cargo:rerun-if-changed={}", path.display());
        let stem = path
            .file_stem()
            .and_then(OsStr::to_str)
            .unwrap_or_else(|| panic!("icon file stem must be valid UTF-8: {}", path.display()));
        if let Some(widget) = to_widget_name(stem) {
            let file_name = path.file_name().and_then(OsStr::to_str).unwrap_or_else(|| {
                panic!("icon file name must be valid UTF-8: {}", path.display())
            });
            output.push_str(&format!(
                "    {widget} => \"{ICON_RESOURCE_PREFIX}{file_name}\",\n"
            ));
        }
    }
    output.push_str("}\n");
    Ok(output)
}

fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));
    let icons_dir = manifest_dir.join("resources").join("icons");
    let out_path = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR not set"))
        .join(GENERATED_BINDINGS_FILE);

    println!("cargo:rerun-if-changed={}", icons_dir.display());

    let bindings = icon_bindings(&icons_dir)
        .expect("failed to generate lucide icon bindings from resources/icons");
    let mut output_file = fs::File::create(&out_path).unwrap_or_else(|error| {
        panic!(
            "failed to create generated bindings at {}: {error}",
            out_path.display()
        )
    });
    output_file
        .write_all(bindings.as_bytes())
        .expect("failed to write generated bindings");
}
