use std::ffi::OsStr;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

const GENERATED_PREVIEW_FILENAME: &str = "icon_preview_rows.rs";
const ICONS_PER_ROW: usize = 8;
const ICON_LABEL_FONT_SIZE: usize = 8;

fn to_widget_name(icon_stem: &str) -> Option<String> {
    let mut widget = String::from("Icon");
    let mut has_part = false;

    for part in icon_stem
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
    {
        has_part = true;
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            widget.push(first.to_ascii_uppercase());
            widget.extend(chars);
        }
    }

    has_part.then_some(widget)
}

fn to_id_name(prefix: &str, icon_stem: &str) -> String {
    let mut id = String::from(prefix);
    for part in icon_stem
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
    {
        id.push('_');
        id.push_str(&part.to_ascii_lowercase());
    }
    id
}

/// Returns generated icon entries as `(widget_name, icon_stem)` tuples.
fn icon_entries(icons_dir: &Path) -> std::io::Result<Vec<(String, String)>> {
    let mut paths: Vec<PathBuf> = fs::read_dir(icons_dir)?
        .filter_map(|entry| entry.ok().map(|value| value.path()))
        .filter(|path| path.extension().is_some_and(|ext| ext == OsStr::new("svg")))
        .collect();
    paths.sort();

    let mut entries = Vec::with_capacity(paths.len());
    for path in paths {
        println!("cargo:rerun-if-changed={}", path.display());

        let stem = path
            .file_stem()
            .and_then(OsStr::to_str)
            .unwrap_or_else(|| panic!("icon file stem must be valid UTF-8: {}", path.display()));

        if let Some(widget_name) = to_widget_name(stem) {
            entries.push((widget_name, stem.to_string()));
        }
    }
    Ok(entries)
}

fn generate_preview(entries: &[(String, String)]) -> String {
    let mut output = String::new();
    let mut row_ids = Vec::new();
    output.push_str("// Generated by makepad-gallery/build.rs. Do not edit manually.\n");
    output.push_str("icon_gallery_page_generated! {\n");

    for (row_index, chunk) in entries.chunks(ICONS_PER_ROW).enumerate() {
        let row_id = format!("icon_row_{row_index}");
        row_ids.push(row_id.clone());
        output.push_str(&format!("    {row_id} := View{{\n"));
        output.push_str("        width: Fill\n");
        output.push_str("        height: Fit\n");
        output.push_str("        flow: Right\n");
        output.push_str("        spacing: 8.0\n");
        for (widget_name, label) in chunk {
            let card_id = to_id_name("icon_card", label);
            output.push_str(&format!("        {card_id} := RoundedView{{\n"));
            output.push_str("            width: 132\n");
            output.push_str("            height: Fit\n");
            output.push_str("            flow: Down\n");
            output.push_str("            spacing: 6.0\n");
            output.push_str("            align: Align{x: 0.5}\n");
            output.push_str("            padding: Inset{left: 8, right: 8, top: 8, bottom: 8}\n");
            output.push_str("            draw_bg +: {\n");
            output.push_str("                color: (shad_theme.color_secondary)\n");
            output.push_str("                border_size: 1.0\n");
            output.push_str("                border_radius: (shad_theme.radius)\n");
            output.push_str("                border_color: (shad_theme.color_outline_border)\n");
            output.push_str("            }\n");
            output.push_str(&format!("            {widget_name}{{\n"));
            output.push_str("                icon_walk: Walk{width: 18, height: 18}\n");
            output.push_str("            }\n");
            output.push_str(&format!(
                "            ShadLabel{{text: \"{}\" draw_text.text_style.font_size: {}}}\n",
                label, ICON_LABEL_FONT_SIZE
            ));
            output.push_str(&format!(
                "            ShadFieldDescription{{width: Fill text: \"{}\" draw_text.text_style.font_size: 8}}\n",
                widget_name
            ));
            output.push_str("        }\n");
        }
        output.push_str("    }\n");
    }

    output.push_str("}\n");
    output.push_str(&format!(
        "const ICON_GALLERY_TOTAL: usize = {};\n",
        entries.len()
    ));
    output.push_str("const ICON_GALLERY_ROW_IDS: &[&str] = &[\n");
    for row_id in &row_ids {
        output.push_str(&format!("    \"{row_id}\",\n"));
    }
    output.push_str("];\n");
    output.push_str("const ICON_GALLERY_ENTRIES: &[IconGalleryEntry] = &[\n");
    for (row_index, chunk) in entries.chunks(ICONS_PER_ROW).enumerate() {
        let row_id = &row_ids[row_index];
        for (widget_name, label) in chunk {
            let card_id = to_id_name("icon_card", label);
            output.push_str(&format!(
                "    IconGalleryEntry{{row_index: {row_index}, row_id: \"{row_id}\", card_id: \"{card_id}\", icon_name: \"{label}\", widget_name: \"{widget_name}\"}},\n"
            ));
        }
    }
    output.push_str("];\n");
    output
}

fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));
    let icons_dir = manifest_dir
        .parent()
        .expect("makepad-gallery should have workspace root parent")
        .join("makepad-icon")
        .join("resources")
        .join("icons");
    println!("cargo:rerun-if-changed={}", icons_dir.display());

    let entries = icon_entries(&icons_dir).expect("failed to read icon resources");
    let generated = generate_preview(&entries);
    let out_path = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR not set"))
        .join(GENERATED_PREVIEW_FILENAME);
    let mut file = fs::File::create(&out_path).unwrap_or_else(|error| {
        panic!(
            "failed to create generated icon preview at {}: {error}",
            out_path.display()
        )
    });
    file.write_all(generated.as_bytes())
        .unwrap_or_else(|error| {
            panic!(
                "failed to write generated icon preview at {}: {error}",
                out_path.display()
            )
        });
}
