use std::ffi::OsStr;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

const GENERATED_PREVIEW_FILENAME: &str = "icon_preview_rows.rs";
const GENERATED_ICON_ENTRIES_FILENAME: &str = "icon_gallery_entries.tsv";
const ICON_LABEL_FONT_SIZE: usize = 12;

fn to_widget_name(icon_stem: &str) -> Option<String> {
    let mut widget = String::from("Icon");
    let mut has_part = false;

    for part in icon_stem
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
    {
        has_part = true;
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            widget.push(first.to_ascii_uppercase());
            widget.extend(chars);
        }
    }

    has_part.then_some(widget)
}

fn to_id_name(prefix: &str, icon_stem: &str) -> String {
    let mut id = String::from(prefix);
    for part in icon_stem
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
    {
        id.push('_');
        id.push_str(&part.to_ascii_lowercase());
    }
    id
}

/// Returns generated icon entries as `(widget_name, icon_stem)` tuples.
fn icon_entries(icons_dir: &Path) -> std::io::Result<Vec<(String, String)>> {
    let mut paths: Vec<PathBuf> = fs::read_dir(icons_dir)?
        .filter_map(|entry| entry.ok().map(|value| value.path()))
        .filter(|path| path.extension().is_some_and(|ext| ext == OsStr::new("svg")))
        .collect();
    paths.sort();

    let mut entries = Vec::with_capacity(paths.len());
    for path in paths {
        println!("cargo:rerun-if-changed={}", path.display());

        let stem = path
            .file_stem()
            .and_then(OsStr::to_str)
            .unwrap_or_else(|| panic!("icon file stem must be valid UTF-8: {}", path.display()));

        if let Some(widget_name) = to_widget_name(stem) {
            entries.push((widget_name, stem.to_string()));
        }
    }
    Ok(entries)
}

fn generate_preview(entries: &[(String, String)]) -> String {
    let mut output = String::new();
    output.push_str("// Generated by makepad-gallery/build.rs. Do not edit manually.\n");
    output.push_str("icon_gallery_page_generated! {\n");
    for (widget_name, label) in entries {
        let template_id = to_id_name("icon_entry", label);
        output.push_str(&format!("    {template_id} := RoundedView{{\n"));
        output.push_str("        width: Fill\n");
        output.push_str("        height: 72\n");
        output.push_str("        flow: Right\n");
        output.push_str("        spacing: 12.0\n");
        output.push_str("        align: Align{x: 0.0 y: 0.5}\n");
        output.push_str("        padding: Inset{left: 12, right: 12, top: 0, bottom: 0}\n");
        output.push_str("        draw_bg +: {\n");
        output.push_str("            color: (shad_theme.color_secondary)\n");
        output.push_str("            border_size: 1.0\n");
        output.push_str("            border_radius: (shad_theme.radius)\n");
        output.push_str("            border_color: (shad_theme.color_outline_border)\n");
        output.push_str("        }\n");
        output.push_str("        preview := RoundedView{\n");
        output.push_str("            width: 40\n");
        output.push_str("            height: 40\n");
        output.push_str("            align: Align{x: 0.5 y: 0.5}\n");
        output.push_str("            draw_bg +: {\n");
        output.push_str("                color: (shad_theme.color_muted)\n");
        output.push_str("                border_radius: 10.0\n");
        output.push_str("            }\n");
        output.push_str(&format!("            {widget_name}{{\n"));
        output.push_str("                icon_walk: Walk{width: 18, height: 18}\n");
        output.push_str("                draw_icon.color: (shad_theme.color_primary)\n");
        output.push_str("            }\n");
        output.push_str("        }\n");
        output.push_str("        copy := View{\n");
        output.push_str("            width: Fill\n");
        output.push_str("            height: Fit\n");
        output.push_str("            flow: Down\n");
        output.push_str("            spacing: 4.0\n");
        output.push_str(&format!(
            "            ShadLabel{{text: \"{}\" draw_text.text_style.font_size: {}}}\n",
            label, ICON_LABEL_FONT_SIZE
        ));
        output.push_str(&format!(
            "            ShadFieldDescription{{width: Fill text: \"{}\" draw_text.text_style.font_size: 11}}\n",
            widget_name
        ));
        output.push_str("        }\n");
        output.push_str("    }\n");
    }

    output.push_str("}\n");
    output
}

fn generate_icon_entries_manifest(entries: &[(String, String)]) -> String {
    let mut output = String::new();
    for (widget_name, label) in entries {
        let template_id = to_id_name("icon_entry", label);
        output.push_str(&template_id);
        output.push('\t');
        output.push_str(label);
        output.push('\t');
        output.push_str(widget_name);
        output.push('\n');
    }
    output
}

fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));
    let icons_dir = manifest_dir
        .parent()
        .expect("makepad-gallery should have workspace root parent")
        .join("makepad-icon")
        .join("resources")
        .join("icons");
    println!("cargo:rerun-if-changed={}", icons_dir.display());

    let entries = icon_entries(&icons_dir).expect("failed to read icon resources");
    let generated = generate_preview(&entries);
    let entries_manifest = generate_icon_entries_manifest(&entries);
    let generated_dir = manifest_dir.join("target").join("generated");
    fs::create_dir_all(&generated_dir).unwrap_or_else(|error| {
        panic!(
            "failed to create generated icon preview directory at {}: {error}",
            generated_dir.display()
        )
    });
    let out_path = generated_dir.join(GENERATED_PREVIEW_FILENAME);
    let mut file = fs::File::create(&out_path).unwrap_or_else(|error| {
        panic!(
            "failed to create generated icon preview at {}: {error}",
            out_path.display()
        )
    });
    file.write_all(generated.as_bytes())
        .unwrap_or_else(|error| {
            panic!(
                "failed to write generated icon preview at {}: {error}",
                out_path.display()
            )
        });

    let generated_resources_dir = manifest_dir.join("resources").join("generated");
    fs::create_dir_all(&generated_resources_dir).unwrap_or_else(|error| {
        panic!(
            "failed to create generated icon metadata directory at {}: {error}",
            generated_resources_dir.display()
        )
    });
    let entries_path = generated_resources_dir.join(GENERATED_ICON_ENTRIES_FILENAME);
    fs::write(&entries_path, entries_manifest).unwrap_or_else(|error| {
        panic!(
            "failed to write generated icon metadata at {}: {error}",
            entries_path.display()
        )
    });
}
