use std::fs;
use std::io::Write;
use std::path::PathBuf;

use makepad_icon::ICON_METADATA;

const GENERATED_PREVIEW_FILENAME: &str = "icon_preview_rows.rs";
const ICON_LABEL_FONT_SIZE: usize = 12;

fn to_id_name(prefix: &str, icon_stem: &str) -> String {
    let mut id = String::from(prefix);
    for part in icon_stem
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
    {
        id.push('_');
        id.push_str(&part.to_ascii_lowercase());
    }
    id
}

fn generate_preview() -> String {
    let mut output = String::new();
    output.push_str("// Generated by makepad-gallery/build.rs. Do not edit manually.\n");
    output.push_str("icon_gallery_page_generated! {\n");
    for metadata in ICON_METADATA {
        let template_id = to_id_name("icon_entry", metadata.icon_name);
        output.push_str(&format!("    {template_id} := RoundedView{{\n"));
        output.push_str("        width: Fill\n");
        output.push_str("        height: 72\n");
        output.push_str("        flow: Right\n");
        output.push_str("        spacing: 12.0\n");
        output.push_str("        align: Align{x: 0.0 y: 0.5}\n");
        output.push_str("        padding: Inset{left: 12, right: 12, top: 0, bottom: 0}\n");
        output.push_str("        draw_bg +: {\n");
        output.push_str("            color: (shad_theme.color_secondary)\n");
        output.push_str("            border_size: 1.0\n");
        output.push_str("            border_radius: (shad_theme.radius)\n");
        output.push_str("            border_color: (shad_theme.color_outline_border)\n");
        output.push_str("        }\n");
        output.push_str("        preview := RoundedView{\n");
        output.push_str("            width: 40\n");
        output.push_str("            height: 40\n");
        output.push_str("            align: Align{x: 0.5 y: 0.5}\n");
        output.push_str("            draw_bg +: {\n");
        output.push_str("                color: (shad_theme.color_muted)\n");
        output.push_str("                border_radius: 10.0\n");
        output.push_str("            }\n");
        output.push_str(&format!("            {}{{\n", metadata.widget_name));
        output.push_str("                icon_walk: Walk{width: 18, height: 18}\n");
        output.push_str("                draw_icon.color: (shad_theme.color_primary)\n");
        output.push_str("            }\n");
        output.push_str("        }\n");
        output.push_str("        copy := View{\n");
        output.push_str("            width: Fill\n");
        output.push_str("            height: Fit\n");
        output.push_str("            flow: Down\n");
        output.push_str("            spacing: 4.0\n");
        output.push_str(&format!(
            "            ShadLabel{{text: \"{}\" draw_text.text_style.font_size: {}}}\n",
            metadata.icon_name, ICON_LABEL_FONT_SIZE
        ));
        output.push_str(&format!(
            "            ShadFieldDescription{{width: Fill text: \"{}\" draw_text.text_style.font_size: 11}}\n",
            metadata.widget_name
        ));
        output.push_str("        }\n");
        output.push_str("    }\n");
    }
    output.push_str("}\n");
    output
}

fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));
    let icons_dir = manifest_dir
        .parent()
        .expect("makepad-gallery should have workspace root parent")
        .join("makepad-icon")
        .join("resources")
        .join("icons");
    println!("cargo:rerun-if-changed={}", icons_dir.display());
    for metadata in ICON_METADATA {
        println!(
            "cargo:rerun-if-changed={}",
            icons_dir
                .join(format!("{}.svg", metadata.icon_name))
                .display()
        );
    }

    let generated = generate_preview();
    let out_path = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR not set"))
        .join(GENERATED_PREVIEW_FILENAME);
    let mut file = fs::File::create(&out_path).unwrap_or_else(|error| {
        panic!(
            "failed to create generated icon preview at {}: {error}",
            out_path.display()
        )
    });
    file.write_all(generated.as_bytes())
        .unwrap_or_else(|error| {
            panic!(
                "failed to write generated icon preview at {}: {error}",
                out_path.display()
            )
        });
}
