#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
from pathlib import Path


def to_widget_name(icon_name: str) -> str:
    parts = [part for part in re.split(r"[^a-zA-Z0-9]+", icon_name) if part]
    if not parts:
        raise ValueError(f"Invalid icon name: {icon_name!r}")
    return "Icon" + "".join(part[:1].upper() + part[1:] for part in parts)


def generate_bindings(icons_dir: Path, output: Path) -> None:
    icon_files = sorted(path for path in icons_dir.glob("*.svg") if path.is_file())
    lines = [
        "// Generated by makepad-icon/scripts/generate_lucide_bindings.py",
        "// Regenerate with: python3 scripts/generate_lucide_bindings.py",
        "// Do not edit manually.",
        "define_lucide_icons! {",
    ]
    for icon_file in icon_files:
        stem = icon_file.stem
        widget = to_widget_name(stem)
        lines.append(
            f'    {widget} => "self://resources/icons/{icon_file.name}",'
        )
    lines.append("}")
    lines.append("")

    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {len(icon_files)} icon bindings in {output}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Makepad icon bindings from Lucide SVG resources."
    )
    parser.add_argument(
        "--icons-dir",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "resources" / "icons",
        help="Directory containing Lucide SVG files.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "src" / "lucide_icon_bindings.rs",
        help="Output Rust file path.",
    )
    args = parser.parse_args()

    if not args.icons_dir.is_dir():
        raise SystemExit(f"Icons directory does not exist: {args.icons_dir}")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    generate_bindings(args.icons_dir, args.output)


if __name__ == "__main__":
    main()
