// Generated by makepad-icon/scripts/generate_lucide_bindings.py
// Do not edit manually.
define_lucide_icons! {
    IconCheck => "self://resources/icons/check.svg",
    IconChevronDown => "self://resources/icons/chevron-down.svg",
    IconChevronLeft => "self://resources/icons/chevron-left.svg",
    IconChevronRight => "self://resources/icons/chevron-right.svg",
    IconCommand => "self://resources/icons/command.svg",
    IconControl => "self://resources/icons/control.svg",
    IconInfo => "self://resources/icons/info.svg",
    IconMenu => "self://resources/icons/menu.svg",
    IconMoreHorizontal => "self://resources/icons/more-horizontal.svg",
    IconOption => "self://resources/icons/option.svg",
    IconSearch => "self://resources/icons/search.svg",
    IconShift => "self://resources/icons/shift.svg",
    IconX => "self://resources/icons/x.svg",
}
